### ISSUE TITLE
Add a plank at the bottom of the page.

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenTerm#6]
Plank is the task bar like thing at the bottom of mac os or other OS.

Keep one application thier at the moment which is the terminal. Use any icon you think looks good for the terminal. Since its only one application the rest of the space will look empty, but thats fine.
![image](https://user-images.githubusercontent.com/12110844/35160873-7a30a8de-fd64-11e7-9be8-bbe60c86011c.png)

**Comment by arpitmisraw** [comment]
I'd like to work on it.

**Comment by gauthamzz** [comment]
sure
